---
title: "sal_eco"
output: html_document
---

<style type="text/css">
body .main-container {
        max-width: 4000px;
    }
</style>

```{r setup, include=FALSE}
library(dplyr)
library(readODS)
library(reshape2)
library(ggplot2)
library(ggbeeswarm)

mydata <- read.csv("js.csv", header = FALSE, stringsAsFactors = FALSE)  # Asia

start_table <- seq(1, nrow(mydata), 9)
end_table <- start_table + 8

mediums <- c("LB10", "BHI", "TSB", "M63")

# empty list to override bind_rows
datalist = list()

for (i in seq(1, ceiling(nrow(mydata)/9))) {
  # read start and end of single table
  x <- start_table[i]
  y <- end_table[i]
  raw_data <- mydata[x:y,]
  # raw_data <- mydata[1:9,] #TEST
  # transform single table
  ODc <- 0.125 
  strains_data <- raw_data[-c(2, 9), -c(1, 12)]
  mresults <- melt(strains_data[-1,] %>% unlist %>% matrix(nrow = 6), varnames = c("row", "col")) %>% 
    mutate(row = factor(row), 
           col = factor(col))
  
  # create and transform plate scheme for single table
  plate_scheme <- sapply(unique(as.integer(strains_data[1,])), function(x) (paste0(x, "-", mediums))) %>% 
    rep(each = 3) %>% 
    matrix(nrow = 6)
  mplate_scheme <- melt(plate_scheme, varnames = c("row", "col"), value.name = "description") %>% 
    mutate(row = factor(row), 
           col = factor(col))
  
  # create single df from single table
  conditions <- raw_data[1,1] # grab conditions
  all_res <- inner_join(mplate_scheme, mresults, by = c("row" = "row", "col" = "col")) %>% 
    filter(!is.na(description)) %>% 
    mutate(description = as.character(description), 
           strain = sapply(strsplit(description, split = "-"), first),
           medium = sapply(strsplit(description, split = "-"), last),
           temp = sapply(strsplit(conditions, split = " "), first), 
           replicate = rep(1:3, times = nrow(mplate_scheme)/3),
           surface = sapply(strsplit(conditions, split = " "), last),
           plate_no = rep(i, times = nrow(mplate_scheme)))  %>%                       # DK liczpa powtórzeń
    # ) %>% 
    # rep(1:3, by = 12, each = 12, times = 4)
    # select(strain, medium, value, replicate, temp, surface) %>% 
    filter(!is.na(value))
  
  # add to table above strength of biofilm formation
  all_res$value <- as.numeric(as.character(all_res$value))
  
  OD <- all_res %>% group_by(strain, medium, description, temp, surface) %>% summarise(avg = mean(value)) %>% 
    mutate(strength = as.character(sapply(avg, function(x) {
      cut(x, breaks = c(0, ODc, 2*ODc, 4*ODc, 10), labels = c("no biofilm", "weak", "moderate", "strong"))
    })))
  
  datalist[[i]] <- inner_join(all_res, OD, by = c("strain", "medium", "temp", "surface"))
} 

all_results <- do.call(rbind, datalist)

# Asia
all_results <- all_results %>% 
  mutate(rep_no = rep(1:3, each = 240, times = (nrow(all_results)/720)))



mydata_D <- read.csv("dk_0912.csv", header = FALSE, stringsAsFactors = FALSE)  # Dominika

start_table_D <- seq(1, nrow(mydata_D), 9)
end_table_D <- start_table_D + 8

mediums <- c("LB10", "BHI", "TSB", "M63")

# empty list to override bind_rows
datalist = list()

for (i in seq(1, ceiling(nrow(mydata_D)/9))) {
  # read start and end of single table
  x <- start_table_D[i]
  y <- end_table_D[i]
  raw_data <- mydata_D[x:y,]
  # raw_data <- mydata[1:9,] #TEST
  # transform single table
  ODc <- mean(as.numeric(raw_data[7:8, 12]))        # neg control for biofilm strength assumption  
  strains_data <- raw_data[-c(2, 9), -c(1, 12)]
  mresults <- melt(strains_data[-1,] %>% unlist %>% matrix(nrow = 6), varnames = c("row", "col")) %>% 
    mutate(row = factor(row), 
           col = factor(col))
  
  # create and transform plate scheme for single table
  plate_scheme <- sapply(unique(as.integer(strains_data[1,])), function(x) (paste0(x, "-", mediums))) %>% 
    rep(each = 3) %>% 
    matrix(nrow = 6)
  mplate_scheme <- melt(plate_scheme, varnames = c("row", "col"), value.name = "description") %>% 
    mutate(row = factor(row), 
           col = factor(col))
  
  # create single df from single table
  conditions <- raw_data[1,1] # grab conditions
  all_res <- inner_join(mplate_scheme, mresults, by = c("row" = "row", "col" = "col")) %>% 
    filter(!is.na(description)) %>% 
    mutate(description = as.character(description), 
           strain = sapply(strsplit(description, split = "-"), first),
           medium = sapply(strsplit(description, split = "-"), last),
           temp = sapply(strsplit(conditions, split = " "), first), 
           replicate = rep(1:3, times = nrow(mplate_scheme)/3),
           surface = sapply(strsplit(conditions, split = " "), last),
           plate_no = rep(i, times = nrow(mplate_scheme)),             # if we have strains on more than 1 plate, do przerobienia na zwykłe repeat zamiast numeru płytki
           rep_no = ifelse(i<51, "1", "2"))  %>%                       # DK liczpa powtórzeń
    # ) %>% 
    # rep(1:3, by = 12, each = 12, times = 4)
    # select(strain, medium, value, replicate, temp, surface) %>% 
    filter(!is.na(value))
  
  # add to table above strength of biofilm formation
  all_res$value <- as.numeric(as.character(all_res$value))
  
  OD <- all_res %>% group_by(strain, medium, description, temp, surface) %>% summarise(avg = mean(value)) %>% 
    mutate(strength = as.character(sapply(avg, function(x) {
      cut(x, breaks = c(0, ODc, 2*ODc, 4*ODc, 10), labels = c("no biofilm", "weak", "moderate", "strong"))
    })))
  
  datalist[[i]] <- inner_join(all_res, OD, by = c("strain", "medium", "temp", "surface"))
} 

all_results_D <- do.call(rbind, datalist)

# sort by strain
all_results_D <- all_results_D[order(all_results_D$strain),] %>%
  mutate(ID = seq(1:nrow(all_results_D)))
```

## Wszystkie wyniki jako boxplot

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=20, fig.height=12}

all_results %>% 
  group_by(strain, medium, rep_no, temp, surface) %>% 
  mutate(conditions = paste(temp, surface)) %>% 
  ggplot(aes(x = strain, y = value, color = conditions)) +
  geom_boxplot() +
  facet_wrap(c("medium", "rep_no"), ncol=3) +
  theme_bw(base_size = 12) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        legend.position = "bottom")
```

## Śednie wyników

```{r, echo=FALSE,message=FALSE,warning=FALSE,fig.width=9,fig.height=5}
all_results %>% 
  # filter(medium == "LB10") %>%
  mutate(conditions = paste(temp, surface)) %>% 
  group_by(strain, medium, conditions, rep_no) %>%
  summarise(value = median(value)) %>%
  ggplot(aes(x = strain, y = value, color = conditions)) +
  geom_point(size = 3) +
  facet_wrap(c("medium", "rep_no"), ncol = 3) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## Jakie biofilmy

```{r, echo=FALSE,message=FALSE,warning=FALSE,fig.width=9,fig.height=5}
all_results %>% 
  mutate(conditions = paste(temp, surface)) %>% 
  # filter(temp == "37") %>%
  ggplot(aes(x = strain, y = rep_no, fill = strength)) +
  geom_tile(color = "black") +
  facet_wrap(c("medium", "conditions"), ncol = 4) +
  theme_bw() +
  scale_fill_discrete("Conditions") +
  scale_x_discrete("Strain") +
  # scale_y_discrete("Biofilm forming strength", limits=c("no biofilm","weak", "moderate", "strong")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```






## Wszystkie wyniki

```{r, echo=FALSE,message=FALSE,warning=FALSE,fig.width=9,fig.height=5}
all_results_D %>% 
  ggplot(aes(x = strain, y = value, color = rep_no)) +
  geom_quasirandom() +
  facet_wrap(~ medium, ncol = 1) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6))
```

## Śednie wyników

```{r, echo=FALSE,message=FALSE,warning=FALSE,fig.width=9,fig.height=5}
all_results_D %>%
  group_by(strain, medium, rep_no) %>%
  summarise(value = median(value)) %>%
  ggplot(aes(x = strain, y = value, color = rep_no)) +
  geom_point(size = 3) +
  facet_wrap(~ medium, ncol = 1) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6))
```

## Jakie biofilmy

```{r, echo=FALSE,message=FALSE,warning=FALSE,fig.width=9,fig.height=5}
all_results_D %>% 
  mutate(conditions = paste(temp, surface)) %>% 
  ggplot(aes(x = strain, y = rep_no, fill = strength)) +
  geom_tile(color = "black") +
  facet_wrap(c("medium"), ncol = 1) +
  theme_bw() +
  scale_x_discrete("Strain") +
  # scale_y_discrete("Biofilm forming strength", limits=c("no biofilm","weak", "moderate", "strong")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6))
```

## Jakie biofilmy

```{r, echo=FALSE,message=FALSE,warning=FALSE,fig.width=9,fig.height=5}
all_results_D[1:2976,] %>% 
  mutate(conditions = paste(temp, surface)) %>% 
  ggplot(aes(x = strain, y = rep_no, fill = strength)) +
  geom_tile(color = "black") +
  facet_wrap(c("medium"), ncol = 1) +
  theme_bw() +
  scale_x_discrete("Strain") +
  # scale_y_discrete("Biofilm forming strength", limits=c("no biofilm","weak", "moderate", "strong")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6))
```

## Jakie biofilmy

```{r, echo=FALSE,message=FALSE,warning=FALSE,fig.width=9,fig.height=5}
all_results_D[2977:nrow(all_results_D),] %>% 
  mutate(conditions = paste(temp, surface)) %>% 
  ggplot(aes(x = strain, y = rep_no, fill = strength)) +
  geom_tile(color = "black") +
  facet_wrap(c("medium"), ncol = 1) +
  theme_bw() +
  scale_x_discrete("Strain") +
  # scale_y_discrete("Biofilm forming strength", limits=c("no biofilm","weak", "moderate", "strong")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6))
```